<template><div class="mx-auto max-w-7xl"><div class="mb-6"><h1 class="font-heading text-4xl text-white">Contact <span class="text-brand-red">Submissions</span></h1><p class="mt-1 text-sm text-brand-grey">Manage contact form and finance inquiries</p></div>
<div v-if="loading" class="space-y-3"> <div v-for="i in 5" :key="i" class="animate-pulse rounded-sm border border-brand-grey/20 p-4"><div class="h-5 w-64 rounded bg-brand-grey/10" /><div class="mt-2 h-4 w-40 rounded bg-brand-grey/10" /></div> </div>
<div v-else-if="items.length === 0" class="rounded-sm border border-dashed border-brand-grey/20 p-12 text-center"><MessageSquare class="mx-auto h-12 w-12 text-brand-grey/40" /><p class="mt-4 font-display text-xl tracking-display text-brand-grey">No Submissions</p></div>
<div v-else class="overflow-x-auto rounded-sm border border-brand-grey/20"><table class="w-full text-left text-sm"><thead class="border-b border-brand-grey/20 bg-brand-black/80"><tr><th class="px-4 py-3 font-display text-xs tracking-display text-brand-grey uppercase">Name</th><th class="px-4 py-3 font-display text-xs tracking-display text-brand-grey uppercase">Email</th><th class="px-4 py-3 font-display text-xs tracking-display text-brand-grey uppercase">Subject</th><th class="px-4 py-3 font-display text-xs tracking-display text-brand-grey uppercase">Category</th><th class="px-4 py-3 font-display text-xs tracking-display text-brand-grey uppercase">Date</th><th class="px-4 py-3 font-display text-xs tracking-display text-brand-grey uppercase">Status</th><th class="px-4 py-3 font-display text-xs tracking-display text-brand-grey uppercase text-right">Actions</th></tr></thead><tbody class="divide-y divide-brand-grey/10"><tr v-for="c in items" :key="c.id" class="transition-colors hover:bg-white/5"><td class="px-4 py-3 text-white">{{ c.name }}</td><td class="px-4 py-3 text-brand-grey">{{ c.email }}</td><td class="px-4 py-3 text-brand-grey">{{ c.subject || '-' }}</td><td class="px-4 py-3"><Badge>{{ c.category }}</Badge></td><td class="px-4 py-3 text-brand-grey">{{ formatDate(c.created) }}</td><td class="px-4 py-3"><Badge :variant="c.status === 'new' ? 'warning' : c.status === 'contacted' ? 'secondary' : 'success'">{{ c.status }}</Badge></td><td class="px-4 py-3 text-right"><Button variant="ghost" size="sm" @click="openDetail(c)">View</Button></td></tr></tbody></table></div>
<Teleport to="body"><div v-if="showModal" class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 overflow-y-auto" @click.self="showModal=false"><div class="w-full max-w-lg rounded-sm border border-brand-grey/30 bg-brand-black p-6"><h2 class="font-display text-xl tracking-display text-white">{{ editingItem?.subject || 'Message' }}</h2><p class="mt-1 text-sm text-brand-grey">{{ editingItem?.name }} &lt;{{ editingItem?.email }}&gt;</p><div class="mt-4 rounded-sm bg-brand-grey/5 p-4"><p class="text-sm text-white whitespace-pre-wrap">{{ editingItem?.message }}</p></div><div class="mt-4"><label class="mb-1.5 block text-xs font-display tracking-display text-brand-grey uppercase">Status</label><select v-model="updateForm.status" class="input-field w-full"><option value="new">New</option><option value="contacted">Contacted</option><option value="resolved">Resolved</option></select></div><div class="mt-6 flex justify-end gap-3"><Button variant="ghost" @click="showModal=false">Close</Button><Button :disabled="saving" @click="saveUpdate">{{ saving ? 'Saving...' : 'Update Status' }}</Button></div></div></div></Teleport>
</div></template>
<script setup lang="ts">
import { MessageSquare } from 'lucide-vue-next'
import { usePB } from '~/composables/usePocketBase'
import { useToast } from '~/composables/useToast'
import { useConfirm } from '~/composables/useConfirm'
import { formatDate } from '~/composables/useFormat'
definePageMeta({ layout: 'dashboard', middleware: 'auth', roles: ['admin'] })
useHead({ title: 'Contacts - Nairobi Powerbikes' })
const pb = usePB(); const toast = useToast(); const confirmDlg = useConfirm(); const loading = ref(true); const saving = ref(false)
const items = ref<any[]>([]); const showModal = ref(false); const editingItem = ref<any>(null)
const updateForm = ref({ status: 'new' })

function openDetail(c: any) { editingItem.value = c; updateForm.value = { status: c.status || 'new' }; showModal.value = true }
async function saveUpdate() { saving.value = true; try { await pb.collection('contacts').update(editingItem.value.id, updateForm.value); toast.add({ type: 'success', title: 'Status updated successfully' }); showModal.value = false; await loadData() } catch (e: any) { toast.add({ type: 'error', title: 'Failed to update', message: e?.message || 'Something went wrong' }) } finally { saving.value = false } }
async function loadData() { try { const res = await pb.collection('contacts').getList(1, 100, { sort: '-created' }); items.value = res.items as any[] } catch (e) { console.error(e) } finally { loading.value = false } }
onMounted(() => loadData())
</script>
