/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
  "createRule": "@request.auth.role = 'admin'",
  "deleteRule": "@request.auth.role = 'admin'",
  "fields": [
    {
      "autogeneratePattern": "[a-z0-9]{15}",
      "help": "",
      "hidden": false,
      "id": "text3208210256",
      "max": 15,
      "min": 15,
      "name": "id",
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "hidden": false,
      "id": "40e82693ce671d6",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "customer",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "cascadeDelete": false,
      "collectionId": "pbc_1020517649",
      "hidden": false,
      "id": "5e00e6e9c058259",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "motorcycle",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "relation"
    },
    {
      "help": "",
      "hidden": false,
      "id": "b2dfc278aec9af0",
      "max": 100,
      "min": 1,
      "name": "quantity",
      "onlyInt": true,
      "presentable": false,
      "required": true,
      "system": false,
      "type": "number"
    },
    {
      "help": "",
      "hidden": false,
      "id": "b2327fb80701e14",
      "max": null,
      "min": 0,
      "name": "original_price",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "help": "",
      "hidden": false,
      "id": "360b9e392e06b0f",
      "max": null,
      "min": 0,
      "name": "unit_discount",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "help": "",
      "hidden": false,
      "id": "38a87b8ffcdc7d5",
      "max": null,
      "min": 0,
      "name": "additional_charges",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "help": "",
      "hidden": false,
      "id": "706008ac571e226",
      "max": null,
      "min": 0,
      "name": "unit_price",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "help": "",
      "hidden": false,
      "id": "b11fb1a11d13134",
      "max": null,
      "min": 0,
      "name": "sale_value",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "help": "",
      "hidden": false,
      "id": "c8ae5486f62bca1",
      "max": null,
      "min": 0,
      "name": "total_payable",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "fe740ac251a9c4a",
      "max": 500,
      "min": 0,
      "name": "discount_reason",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": false,
      "system": false,
      "type": "text"
    },
    {
      "hidden": false,
      "id": "0a4f58da4fcb459",
      "maxSelect": 1,
      "name": "payment_type",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "select",
      "values": [
        "full",
        "financing",
        "installment"
      ]
    },
    {
      "hidden": false,
      "id": "699333f976168b3",
      "maxSelect": 1,
      "name": "payment_method",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "select",
      "values": [
        "M-Pesa",
        "Bank Transfer",
        "Bank Deposit",
        "Cash",
        "Card",
        "Cheque",
        "Other"
      ]
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "c128bf7d465be1d",
      "max": 200,
      "min": 0,
      "name": "payment_reference",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": false,
      "system": false,
      "type": "text"
    },
    {
      "hidden": false,
      "id": "cc60c4d034696c7",
      "maxSelect": 1,
      "name": "status",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "select",
      "values": [
        "draft",
        "pending",
        "reserved",
        "confirmed",
        "financed",
        "partially_paid",
        "fully_paid",
        "completed",
        "cancelled"
      ]
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "hidden": false,
      "id": "8183a125e60ba54",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "sold_by",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "help": "",
      "hidden": false,
      "id": "6c2a4ef2ed3c716",
      "max": "",
      "min": "",
      "name": "sale_date",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "date"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "67b649a69ee1e66",
      "max": 2000,
      "min": 0,
      "name": "notes",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": false,
      "system": false,
      "type": "text"
    },
    {
      "hidden": false,
      "id": "5b2a522d82090c0",
      "name": "stock_deducted",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "hidden": false,
      "id": "f6e1d5dcbacbfc6",
      "name": "reserved_hold",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "help": "",
      "hidden": false,
      "id": "3d13274f4a1190f",
      "max": null,
      "min": 0,
      "name": "amount_paid",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bbcd51513d99b96",
      "max": null,
      "min": 0,
      "name": "outstanding",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "84e24afcf22a41c",
      "max": 500,
      "min": 0,
      "name": "cancel_reason",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": false,
      "system": false,
      "type": "text"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "autodate4372818527",
      "name": "created",
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "autodate8747864736",
      "name": "updated",
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": false,
      "type": "autodate"
    }
  ],
  "id": "pbc_612fd4eef2aa",
  "indexes": [
    "CREATE INDEX `idx_sales_customer` ON `sales` (`customer`)",
    "CREATE INDEX `idx_sales_motorcycle` ON `sales` (`motorcycle`)",
    "CREATE INDEX `idx_sales_status` ON `sales` (`status`)"
  ],
  "listRule": "@request.auth.role = 'admin' || (@request.auth.id = customer && customer != null)",
  "name": "sales",
  "system": false,
  "type": "base",
  "updateRule": "@request.auth.role = 'admin'",
  "viewRule": "@request.auth.role = 'admin' || (@request.auth.id = customer && customer != null)"
})
  return app.save(collection)
}, (app) => {
  const collection = app.findCollectionByNameOrId('sales')
  return app.deleteCollection(collection)
})
